coffee_stats_homepage:
    pattern:  /
    defaults: { _controller: CoffeeStatsBundle:Default:dashboard }

coffee_stats_tests_data:
    pattern:  /test_data
    defaults: { _controller: CoffeeStatsBundle:Test:data }

coffee_stats_add_coffee_stock:
    pattern: /coffee/add
    defaults: {_controller: CoffeeStatsBundle:Coffee:add}
    requirements:
        _method:  POST