parameters:
#    coffee_stats.example.class: CoffeeStats\Bundle\CoffeeStatsBundle\Example

services:
#    coffee_stats.example:
#        class: %coffee_stats.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
