parameters:
#    coffee_stats.example.class: CoffeeStats\Bundle\CoffeeStatsBundle\Example

services:
#    coffee_stats.example:
#        class: %coffee_stats.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    coffee_user.registration.form.type:
        class: CoffeeStats\Bundle\CoffeeStatsBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: coffee_user_registration }